// src/app/models/revision.model.ts
export interface Revision {
  id?: number; // Optional ID, automatically generated by the backend
  fechaRevision: Date; // Date of the revision
  resultadoRevision: boolean; // Result of the revision (true for approved, false for rejected)
  vehiculoPlaca: string; // License plate of the associated vehicle
  empleadoUsername?: string; // Username of the employee in charge (optional, backend assigns it if omitted)
}
